In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('/workspaces/customer_chrun_prediction/data/customer_churn_dataset.csv')

In [5]:
df.head(2)

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.4,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.2,Month-to-month,Debit,DSL,No,No,2,No

In [6]:
# Check for null values
print(df.isnull().sum())

customer_id            0
tenure                 0
monthly_charges        0
total_charges          0
contract               0
payment_method         0
internet_service    2013
tech_support           0
online_security        0
support_calls          0
churn                  0
dtype: int64

In [12]:
# Fill na with empty string
df['internet_service'] = df['internet_service'].fillna('')

In [13]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [15]:
# check for un realistic values
df.describe()

,customer_id,tenure,monthly_charges,total_charges,support_calls
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,10000.500000,36.467450,70.010531,2543.979209,1.51255
std,5773.647028,20.773984,28.890239,1882.949804,1.23524
min,1.000000,1.000000,20.000000,20.230000,0.00000
25%,5000.750000,18.000000,45.210000,1045.837500,1.00000
50%,10000.500000,36.000000,70.090000,2096.495000,1.00000
75%,15000.250000,54.000000,95.072500,3690.337500,2.00000
max,20000.000000,72.000000,120.000000,8629.920000,8.00000

There is no unrealistc value should be aware of.

In [16]:
# Save clean data
df.to_csv('/workspaces/customer_chrun_prediction/data/processed/clean_customer_churn_dataset.csv', index=False)